# Generated by Django 3.2.3 on 2021-06-30 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_c', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13)),
                ('nombre_cli', models.CharField(default='', max_length=50)),
                ('apellido_cli', models.CharField(default='', max_length=50)),
                ('fecha_nac', models.DateTimeField(verbose_name='Fecha de nacimiento del cliente')),
                ('correo', models.CharField(max_length=50)),
                ('direccion', models.CharField(default=' ', max_length=100)),
                ('contrasena', models.CharField(max_length=50)),
                ('contrasena_val', models.CharField(max_length=50)),
                ('comuna', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='pasteleria.comuna')),
            ],
        ),
    ]
